:PROPERTIES:
:ID:       c620b007-1376-4f39-9808-5ff9ff487e93
:ROAM_ALIASES: DNS
:END:
#+title: Domain Name System
#+filetags: :Networking:Cybersecurity:

* What is a DNS?
Domain Name System (DNS) is an important protocol in [[id:c702e8f9-1347-486d-81b1-be99b1d46338][networking]]. It provides a way for devices to communicate with other devices on the Internet without remembering complex numbers.

* Domain Hierarchy
** TLD
A Top-Level Domain (TLD) is the most righthand part of a domain name, for example, ~.com~.

There are two types of TLD:
- gTLD (Generic Top-Level Domain)
Historically, gTLD was meant to tell the user the domain name's purpose; for example:
  + ~.com~ is for commercial purposes.
  + ~.org~ is for an organisation.
  + ~.edu~ is for education.
  + ~.gov~ is for a government entity.
- ccTLD (Country Code Top-Level Domain)
  ccTLD is used for geographical purposes; for example:
  + ~.ca~ for sites based in Canada.
  + ~.co.il~ for sites based in Israel.

** SLD
A Second-Level Domain (SLD) is the middle part of a domain name (ignoring ~http://~ and ~www~). For example, in ~google.com~, ~google~ is the SLD.

** Subdomain
A subdomain sits on the left-hand side of the SLD using a period to seperate it; for example, in the name ~docs.google.com~, ~docs~ is the subdomain.

* Record Types
#+begin_quote
DNS records (aka zone files) are instructions that live in authoritative DNS servers and provide information about a domain including what IP address is associated with that domain and how to handle requests for that domain. These records consist of a series of text files written in what is known as DNS syntax. DNS syntax is just a string of characters used as commands that tell the DNS server what to do.
#+end_quote

** Common Records

- ~A~ Record
  These records resolve to IPv4 addresses.
- ~AAAA~ Record
  These record resolve to IPv6 addresses.
- ~CNAME~ Record
  These record resolve to another domain name, for example, some online shops are viewd as ~store.site.com~, which returs a CNAME record of ~shops.shopify.com~. Another DNS request would be made to the new record to work out the IP address.
- ~MX~ Record
  These record resolve to the address of the server that handle the email for the domain you are querying, for example, ~example.com~ MX record could be ~mailhost1.example.com~. These record come with a priority flag. This tells the client in which order to try the servers.
- ~TXT~ Record
  These records are free text fields where any text-based data can be stored. A common use for TXT records is to list servers that have the authority to send an email on behalf of the domain.

* What Happens When A Making a DNS Request?
1) A domain request is made. If the address is in the local cache then its served immediately. Otherwise, a request to the recursive DNS server will be made.
2) A recursive DNS server is usually provided by the ISP. The server also has a local cache of recently looked up domain names. If the domain is cached then its served back to the requesting device. Otherwise a request to the Internet's root DNS server is made.
3) The root server redirects to the correct TLD server.
4) The TLD server holds records for where to find the authoritative server to answer the DNS request. The authoritative server is often also known as the nameserver for the domain. For example, a domain hosted on cloudflare servers, will be in cloudflare's nameservers.
5) The authoritative DNS server is the one responsible for storing the DNS records for a particular domain name.

DNS records all come with a Time-To-Live (TTL) value.

You can use ~nslookup~ to query Internet name servers interactively.

* Resources
- Cloudflare's [[https://www.cloudflare.com/learning/dns/what-is-dns/][article]] about DNS.
- TryHackMe's DNS in Detail room.
