:PROPERTIES:
:ID:       2a8da6c9-ff7d-45a2-b0fd-9fe91fefd738
:ROAM_ALIASES: HTTPS HTTP
:END:
#+title: HyperText Transfer Protocol
#+filetags: :Protocol:Networking:

* Overview
HTTP is the set of rules used for communicating with web servers for the transmitting of webpage data (HTML, Images, Videos, etc...). There are two main kinds of HTTP messages: requests and responses. It sits in the application layer in the [[id:b741e7dd-a3cd-49aa-8cd4-a6633340adcf][OSI Model]]. It is built on top of [[id:ca5aa1c6-9074-46d1-aebf-1f7970f6a8f8][TCP]] but it can also be adapted to work with unreliable protocols such as [[id:9a47d66f-cf42-445c-9685-aa3c17eebc25][UDP]].

By default HTTP traffic is not encrypted, this means that anyone who is monitoring the session can see all requests and responses and know exactly what information someone is asking for, sending, or receiving. This is where HTTPS comes in to play. HTTPS uses TLS (or SSL) to encrypt HTTP requests and responses.

HTTPS gives an assurance that our device is talking to the correct web server. The reason behind this is that any content that the server send to our device needs to be decrypted using a public key that agrees with the private key which was agreed upon in the initial phase of handshake between the two devices. Only devices that contain the private key can decrypte information encrypted with the corresponding public key.

* HTTP Versions
A difference between HTTP/1.1 and HTTP/1.0 is that the ~Host~ request headers is mandatory.

* HTTP Request and Respond
HTTP *requests* are generated by a user's browser as the user interacts with web properties. If a user clicks a hyperlink or inputs a [[id:1ec5d57d-b0df-4429-bc7e-aa6dfe97b381][URL]] directly, the browser will send an HTTP GET request for the content that appears on that page. HTTP requests go to some server (origin or proxy caching) and that server will generate an HTTP *response*. HTTP responses are answers to HTTP requests. All HTTP messages consist of one or more headers, each on a separate line, followed by a mandatory blank line, followed by an optional message body.

The first line of every HTTP request consists of three items:
1. A verb indicating the HTTP method.
2. The resource being requested, together with an optional query string.
3. The HTTP version being used.

The first line of every HTTP response consists of three items:
1. The HTTP version being used.
2. A numeric status code.
3. A text describing the status of the response.

A GET request looks like this:
#+begin_example
GET /hello.txt HTTP/1.1
User-Agent: curl/7.63.0 libcurl/7.63.0 OpenSSL/1.1.l zlib/1.2.11
Host: www.example.com
Accept-Language: en
#+end_example

A response looks like this:
#+begin_example
HTTP/1.1 200 OK
Date: Wed, 30 Jan 2019 12:14:39 GMT
Server: Apache
Last-Modified: Mon, 28 Jan 2019 11:17:01 GMT
Accept-Ranges: bytes
Content-Length: 12
Vary: Accept-Encoding
Content-Type: text/plain

Hello World!
#+end_example

If we were to use HTTPS, then the GET request would look like this:
#+begin_example
t8Fw6T8UV81pQfyhDkhebbz7+oiwldr1j2gHBB3L3RFTRsQCpaSnSBZ78Vme+DpDVJPvZdZUZHpzbbcqmSW1+3xXGsERHg9YDmpYk0VVDiRvw1H5miNieJeJ/FNUjgH0BmVRWII6+T4MnDwmCMZUI/orxP3HGwYCSIvyzS3MpmmSe4iaWKCOHQ==
#+end_example

* HTTP Methods
HTTP methods are a way for the client to show their intended action when making an HTTP request. The most common requests are:
- *GET* - Used for getting information from the web server.
- *HEAD* -  functions in the same way as a GET request, except that the server should not return a message body in its response. The server should return the same headers that it would have returned to the corresponding GET request. Hence, this method can be used to check whether a resource is present before making a GET request for it.
- *POST* - Used for submitting data to the web server and potentially creating new records.
- *TRACE* - Used for diagnostics. The server should return in the respones body the exact content of the request message it received. This is useful for checking requests sent through a proxy before reaching the server.
- *OPTION* - Used for asking the server what HTTP methods are available to a resource. The response contains an ~Allow~ header that lists available  methods.
- *PUT* - Used for submitting data to a web server to update information.
- *DELETE* Used for deleting information/records from a web server.

* HTTP Headers
- The ~Host~ header is used to specify the hostname that appeared in the full URL being accessed.
- The ~Referer~ header is used to indicate the URL from which the request was originated.
- The ~User-Agent~ header is used to provide information about the browser or other client software that generated the request.
- The ~Cookie~ header is used to submit additional parameters that the server has issued to the client.
- The ~Server~ header contains a banner indicating the web server software being used, and sometimes other details such as installed modules and the server operating system.
- The ~Ser-Cookie~ header is issuing the browser a further cookie.
- The ~Pragma~ header is instructing the browser not to store the response in its cache.
- The ~Expires~ header indicates that the response content expired in the past and so shouldn't be cached.
- The ~Content-Type~ header indicates that the type of data in the body of this message.
- The ~Content-Length~ header indicates the length of the message body in bytes.
- The ~Authorization~ header includes an authentication token that is sent with every subsequent request by the browser.
- The ~Connection~ header instructs a server on whether to keep the TCP connection alive after receiving the request or close it.
- The ~Accept~ header tells the server what type of content it is willing to accept.

* HTTP Status Code
When an HTTP server responds, the first line always contains a status code informing the client of the outcome of their request and also potentially how to handle it. These status codes can be broken down into 5 different ranges:
- Information Response (100-199): These are sent to tell hte client the first part of their request has been accepted and they should continue sending the rest of their request.
- Success (200-299): These are sent to tell hte client that the reqest was successful.
- Redirection (300-399): These are sent to the client to redirect their request to another resource.
- Client Errors (400-499): These are sent to inform the client that there was an error in their request.
- Server Errors (500-599): These are sent to inform the client that there was an error in the server side, usually a problem in dealing with the request.

Some of the most common requests are:

| Status Code                  | Meaning                                                                  |
|------------------------------+--------------------------------------------------------------------------|
| 200 - OK                     | The request was completed successfully                                   |
| 201 - Created                | A resource has been created                                              |
| 301 - Permanent Redirect     | Usually means that the page has moved somewhere else                     |
| 302 - Temporary Redirect     | Means a temporary change, could change again                             |
| 400 - Bad Request            | Means that there was a problem with the request.                         |
| 401 - Not Authorised         | The requested page can only be viewd after authorisation from the server |
| 403 - Forbidden              | No permission to view the resource even if logged in                     |
| 405 - Method Not Allowed     | The resource doesn't allow this method request                           |
| 404 - Page Not Found         | The resource doesn't exist                                               |
| 500 - Internal Service Error | The server encountered an error and doesn't know how to handle it        |
| 503 - Service Unavailable    | Server can't handle the request (overloaded, down)                       |

* HTTPS
#+begin_quote
The HTTP protocol uses plain TCP as its transport mechanism, which is unencrypted and therefore can be intercepted by an attacker who is suitably positioned on the network. HTTPS is essentially the same application-layer protocol as HTTP but is tunneled over the secure transport mechanism, Secure Sockets Layer (SSL). This protects the privacy and integrity of data passing over the network, reducing the possibilities for noninvasive interception attacks. HTTP requests and responses function in exactly the same way regardless of whether SSL is used for transport.
#+end_quote



* Resources
- Wikipedia articles on HTTP and HTTPS.
- Cloudflare article on "Why is HTTP not secure? | HTTP vs. HTTPS".
- TryHackMe's room on HTTP.
