:PROPERTIES:
:ID:       2a8da6c9-ff7d-45a2-b0fd-9fe91fefd738
:ROAM_ALIASES: HTTP
:END:
#+title: HyperText Transfer Protocol
#+filetags: :Protocol:Networking:

* Overview
HTTP is the set of rules used for communicating with web servers for the transmitting of webpage data (HTML, Images, Videos, etc...). There are two main kinds of HTTP messages: requests and responses. It sits in the application layer in the [[id:b741e7dd-a3cd-49aa-8cd4-a6633340adcf][OSI Model]]. It is built on top of [[id:ca5aa1c6-9074-46d1-aebf-1f7970f6a8f8][TCP]] but it can also be adapted to work with unreliable protocols such as [[id:9a47d66f-cf42-445c-9685-aa3c17eebc25][UDP]].

By default HTTP traffic is not encrypted, this means that anyone who is monitoring the session can see all requests and responses and know exactly what information someone is asking for, sending, or receiving. This is where HTTPS comes in to play. HTTPS uses TLS (or SSL) to encrypt HTTP requests and responses.

HTTPS gives an assurance that our device is talking to the correct web server. The reason behind this is that any content that the server send to our device needs to be decrypted using a public key that agrees with the private key which was agreed upon in the initial phase of handshake between the two devices. Only devices that contain the private key can decrypte information encrypted with the corresponding public key.

* HTTP Request and Respond
HTTP *requests* are generated by a user's browser as the user interacts with web properties. If a user clicks a hyperlink or inputs a [[id:1ec5d57d-b0df-4429-bc7e-aa6dfe97b381][URL]] directly, the browser will send an HTTP GET request for the content that appears on that page. HTTP requests go to some server (origin or proxy caching) and that server will generate an HTTP *response*. HTTP responses are answers to HTTP requests.

A GET request looks like this:
#+begin_example
GET /hello.txt HTTP/1.1
User-Agent: curl/7.63.0 libcurl/7.63.0 OpenSSL/1.1.l zlib/1.2.11
Host: www.example.com
Accept-Language: en
#+end_example

A response looks like this:
#+begin_example
HTTP/1.1 200 OK
Date: Wed, 30 Jan 2019 12:14:39 GMT
Server: Apache
Last-Modified: Mon, 28 Jan 2019 11:17:01 GMT
Accept-Ranges: bytes
Content-Length: 12
Vary: Accept-Encoding
Content-Type: text/plain

Hello World!
#+end_example

If we were to use HTTPS, then the GET request would look like this:
#+begin_example
t8Fw6T8UV81pQfyhDkhebbz7+oiwldr1j2gHBB3L3RFTRsQCpaSnSBZ78Vme+DpDVJPvZdZUZHpzbbcqmSW1+3xXGsERHg9YDmpYk0VVDiRvw1H5miNieJeJ/FNUjgH0BmVRWII6+T4MnDwmCMZUI/orxP3HGwYCSIvyzS3MpmmSe4iaWKCOHQ==
#+end_example

* HTTP methods
HTTP methods are a way for the client to show their intended action when making an HTTP request. The most common requests are:
- *GET Request* - Used for getting information from the web server.
- *POST Request* - Used for submitting data to the web server and potentially creating new records.
- *PUT Request* - Used for submitting data to a web server to update information.
- *DELETE Request* Used for deleting information/records from a web server.

* HTTP Status Code
When an HTTP server responds, the first line always contains a status code informing the client of the outcome of their request and also potentially how to handle it. These status codes can be broken down into 5 different ranges:
- Information Response (100-199): These are sent to tell hte client the first part of their request has been accepted and they should continue sending the rest of their request.
- Success (200-299): These are sent to tell hte client that the reqest was successful.
- Redirection (300-399): These are sent to the client to redirect their request to another resource.
- Client Errors (400-499): These are sent to inform the client that there was an error in their request.
- Server Errors (500-599): These are sent to inform the client that there was an error in the server side, usually a problem in dealing with the request.

Some of the most common requests are:

| Status Code                  | Meaning                                                                  |
|------------------------------+--------------------------------------------------------------------------|
| 200 - OK                     | The request was completed successfully                                   |
| 201 - Created                | A resource has been created                                              |
| 301 - Permanent Redirect     | Usually means that the page has moved somewhere else                     |
| 302 - Temporary Redirect     | Means a temporary change, could change again                             |
| 400 - Bad Request            | Means that there was a problem with the request.                         |
| 401 - Not Authorised         | The requested page can only be viewd after authorisation from the server |
| 403 - Forbidden              | No permission to view the resource even if logged in                     |
| 405 - Method Not Allowed     | The resource doesn't allow this method request                           |
| 404 - Page Not Found         | The resource doesn't exist                                               |
| 500 - Internal Service Error | The server encountered an error and doesn't know how to handle it        |
| 503 - Service Unavailable    | Server can't handle the request (overloaded, down)                       |

* Headers
Common Request Headers:
- Host - Some web servers host multiple websites, if we don't provide a host header, the defualt website is served.
- User-Agent - The browser software and version, some elements of HTML, CSS and javascript are only available to certain browsers.
- Content-Length - How much data the server should expect in the web reqest. This way the server can check if its missing data.
- Accept-Encoding - Tells the web server what type of compression methods the browser supports so the data can be made smaller for transmitting over the internet.
- Cookie - Data sent to the server to help remember your information.

Common Response Headers:
- Set-Cookie - Information to store which gets sent back to the web server on each request.
- Cache-Control - How long to store the content of the respone in the browser's cache before it requests it again.
- Content-Type - Tells the client what type of data is being returned.
- Content-Encoding - What method has been used to compress the data to make it smaller.

* Resources
- Wikipedia articles on HTTP and HTTPS.
- Cloudflare article on "Why is HTTP not secure? | HTTP vs. HTTPS".
- TryHackMe's room on HTTP.
