:PROPERTIES:
:ID:       ae5068d2-077b-4742-9537-22b00396a7bb
:END:
#+title: Programming Black Book

* Rules for Building High-Performance Code
Making the rules is easy, the hard part is figuring out how to apply them in the real world. Examining some working code is always a good way to get a handle on programming concepts.

1. Know where you're going - understand the objective of the software.
2. Make a big map - have an overall program design firmly in mind, so the various parts of the program and the data structures work well together.
3. Make lots of little maps - design an algorithm for each separate part of the overall design.
4. Know the territory - understand exactly how the computer carries out each task.
5. Know when it matters - identify the portions of your program where performance matters, and don't waste time optimizing the rest.
6. Always consider the alternatives 0 don't get stuck on a single approach; odds there's a better way.
7. Know how to turn on the juice - optimize the code as best you know how when it /does/ matter.

* Examples
** 16-bit Checksum
*** Know Where

* Resources
- Michael Abrash's Graphics Programming Black Book Special Edition
