:PROPERTIES:
:ID:       b1346e50-7065-4fa1-81c8-70fff85a17cb
:END:
#+title: Authentication
#+filetags: :webexp:

* Overview
#+begin_quote
Authentication is the process of verifying the identity of a given user or client. In other words, it involves making sure that they really are who they claim to be. At least in part, websites are exposed to anyone who is connected to the internet by design. Therefore, robust authentication mechanisms are an integral aspect of effective web security.
#+end_quote

There are three authentication factors:
1. Knowledge factors such as passwords.
2. Possession factors such as security token.
3. Inherence factors such as fingerprints.

** Authentication vs Authorization
- Authentication is making sure that the user is who he claims to be.
- Authorization is for verifying whether a user is allowed to do something.


* Authentication Vulnerabilities
Most vulnerabilities in authentication arise in one of two ways:
1. Broken Authentication - [[id:25a1de57-6839-445f-bf84-e20b746d9d82][Business Logic Vulnerabilities]] or poor coding in the implementation might allow an attack to bypass the authentication process.
2. Weak Authentication Mechanism - Brute force attacks can be used to guess a password.

* Password-based Authentication
Accounts are associated with a unique username and password which the users enters in a login form to authenticate themselves. The security of the website is comprimised if the attacker knows the secret password or can easily guess it.

** Brute-force Attacks
#+begin_quote
A brute-force attack is when an attacker uses a system of trial and error in an attempt to guess valid user credentials. These attacks are typically automated using wordlists of usernames and passwords. Automating this process, especially using dedicated tools, potentially enables an attacker to make vast numbers of login attempts at high speed.
#+end_quote

** Username enumeration
#+begin_quote
Username enumeration is when an attacker is able to observe changes in the website's behavior in order to identify whether a given username is valid.
#+end_quote

The following list of available information can make brute-force attack easier:
- Status codes - Different status code for correct credentials can be used for enumeration.
- Error messages - Returned error messages can be different when correct information is provided.
- Response time - Some applications only check passwords after validating that the user is valid. Time based attacks can be used to guess passwords or usernames if the application checks the provided information in a loop (one charactor at a time).

* Multi-factor Authentication
#+begin_quote
Many websites rely exclusively on single-factor authentication using a password to authenticate users. However, some require users to prove their identity using multiple authentication factors.
#+end_quote

The full benefit of multi-factor authentication is only achieved by verifying multiple *different* factors.

** Bypassing MFA
If the user is prompted to enter a password then redirected to another page where a token is required, then the user might have already been authenticated, and can simply skip this step by accessing other pages in the website.

** Flawed MFA Logic
If the program does not check that the same user is completing the second step, then an attacker can for example replace a value that the program depends on after authenticating using his own account, such as cookie value, to initiate a code check for another account. If the code can also be brute-forced, then gaining access to another account is made easier.

* Securing Authentication Mechanisms
- Secure user credentials
   Login data should be sent over an encrypted connection. Any attempted HTTP request should be redirected to HTTPS. In addition to encrypted connections, login information should not be reflected in HTTP responses or any publicly accessible page.
- Enforce secure behavior wherever possible
   Implement effective password policies. Make assumptions that users will try the least effort method to bypass those policies.
- Prevent enumeration
   Don't reveal that a user exist upon unsuccessful login attempts. Using generic error messages and returning the same HTTP status code as well as keeping the response time close in both cases is one way to prevent enumeration.
- Implement brute force protection
   Implementing a defense mechanism against brute force login attempts is very crucial. Implementing IP-based rate limiting as well as CAPTCHA tests after reaching a certain limit is a common defense strategy.

* Resources
- Portswigger's articles about authentication ([[https://portswigger.net/web-security/authentication][link]])
